### ISSUE TITLE
Создать тесты для MergeSort_Baseline и MergeSort_InPlace

### ISSUE THREAD

**Issue by bidlomodder** [bidlomodder/PracticeProject#1]
Для работы над клиентской программой и дальнейшей оптимизации сортировки необходимо убедится в корректности работы реализованных алгоритмов. Для этого необходимо составить набор тестов покрывающих основные ситуации, также необходимо оценить время работы алгоритмов в среднем и, для `MergeSort_InPlace`, худшем случаях.

**Comment by Core0ne** [comment]
@bidlomodder, я написал тесты
