### ISSUE TITLE
Обнаружен баг при тесте с пустым массивом

### ISSUE THREAD

**Issue by Core0ne** [bidlomodder/PracticeProject#3]
Тест с пустым массивом не проходит. В алгоритме BaseLine, выскакивает StackOverflowExeption, а в алгоритме InPlace тест проваливается

**Comment by bidlomodder** [comment]
@Core0ne я исправил ошибки, если тебя все устраивает выполни слияние #4

**Comment by Core0ne** [comment]
Изменения #4 приняты
