### ISSUE TITLE
Недостаточно тестов

### ISSUE THREAD

**Issue by bidlomodder** [bidlomodder/PracticeProject#8]
Я добавил реализацию с поддержкой параллелизма, однако проверить ее корректность не представляется возможным т.к. минимальная длинна массива, сортировка которого выполняется параллельно  -  (4096+1), а размеры массивов в тестах не превышают 1000 элементов.

**Comment by Core0ne** [comment]
И шо ты от меня хочешь?

**Comment by bidlomodder** [comment]
Очевидно, хочу что бы ты добавил тестов для параллельной сортировки, @Core0ne  и арбуз.

**Comment by Core0ne** [comment]
@bidlomodder чтобы*. Есть только дыня.

**Comment by Core0ne** [comment]
Добавил тесты, проверяй
